package:
  name: htrc-feature-reader
  version: "1.99"

source:
  path: ../..

build:
  noarch: python # Only needs one build
  # preserve_egg_dir: True
  ignore_prefix_files: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - htrc-feature-reader = htrc-feature-reader:main
    #
    # Would create an entry point called htrc-feature-reader that calls htrc-feature-reader.main()
    - htid2rsync = htrc_features.utils:htid2rsync_cmd

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pytest-runner
    - setuptools
    - six
    - pandas>=0.24
    - numpy
    - pymarc
    - requests
    - rapidjson

  run:
    - python
    - six
    - pandas>=0.24
    - numpy
    - pymarc
    - requests
    - rapidjson

test:
  # Python imports
  imports:
    - htrc_features

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    #- htid2rsync --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - pytest
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/organisciak/htrc-feature-reader
  license: University of Illinois/NCSA Open Source License
  summary: 'Library for working with the HTRC Extracted Features dataset'
  license_family: Proprietary

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
